package pl.com.mnemonic.entities;
// default package
// Generated 2015-04-12 11:10:53 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name = "page", catalog = "renting")
public class Page implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idpage;
	private String pagename;
	private String dirname;
	private Set<Bindpage> bindpages = new HashSet<Bindpage>(0);

	public Page() {
	}

	public Page(String pagename, String dirname) {
		this.pagename = pagename;
		this.dirname = dirname;
	}

	public Page(String pagename, String dirname, Set<Bindpage> bindpages) {
		this.pagename = pagename;
		this.dirname = dirname;
		this.bindpages = bindpages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpage", unique = true, nullable = false)
	public Integer getIdpage() {
		return this.idpage;
	}

	public void setIdpage(Integer idpage) {
		this.idpage = idpage;
	}

	@Column(name = "pagename", nullable = false, length = 80)
	public String getPagename() {
		return this.pagename;
	}

	public void setPagename(String pagename) {
		this.pagename = pagename;
	}

	@Column(name = "dirname", nullable = false, length = 45)
	public String getDirname() {
		return this.dirname;
	}

	public void setDirname(String dirname) {
		this.dirname = dirname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "page")
	public Set<Bindpage> getBindpages() {
		return this.bindpages;
	}

	public void setBindpages(Set<Bindpage> bindpages) {
		this.bindpages = bindpages;
	}

}
