package pl.com.mnemonic.entities;
// default package
// Generated 2015-04-12 11:10:53 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Refueling generated by hbm2java
 */
@Entity
@Table(name = "refueling", catalog = "renting")
public class Refueling implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idrefueling;
	private Bindrole bindrole;
	private Car car;
	private Date date;
	private Float litre;
	private Float kilometers;

	public Refueling() {
	}

	public Refueling(Bindrole bindrole, Car car) {
		this.bindrole = bindrole;
		this.car = car;
	}

	public Refueling(Bindrole bindrole, Car car, Date date, Float litre,
			Float kilometers) {
		this.bindrole = bindrole;
		this.car = car;
		this.date = date;
		this.litre = litre;
		this.kilometers = kilometers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idrefueling", unique = true, nullable = false)
	public Integer getIdrefueling() {
		return this.idrefueling;
	}

	public void setIdrefueling(Integer idrefueling) {
		this.idrefueling = idrefueling;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bindrole_idbindrole", nullable = false)
	public Bindrole getBindrole() {
		return this.bindrole;
	}

	public void setBindrole(Bindrole bindrole) {
		this.bindrole = bindrole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "car_idcar", nullable = false)
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "litre", precision = 12, scale = 0)
	public Float getLitre() {
		return this.litre;
	}

	public void setLitre(Float litre) {
		this.litre = litre;
	}

	@Column(name = "kilometers", precision = 12, scale = 0)
	public Float getKilometers() {
		return this.kilometers;
	}

	public void setKilometers(Float kilometers) {
		this.kilometers = kilometers;
	}

}
