package pl.com.mnemonic.entities;
// default package
// Generated 2015-04-12 11:10:53 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rent generated by hbm2java
 */
@Entity
@Table(name = "rent", catalog = "renting")
public class Rent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idrent;
	private Bindrole bindrole;
	private Car car;
	private Date dateFrom;
	private Date dateTo;
	private String attachment;
	private Date dateregistered;
	private Boolean confirmed;

	public Rent() {
	}

	public Rent(Bindrole bindrole, Car car) {
		this.bindrole = bindrole;
		this.car = car;
	}

	public Rent(Bindrole bindrole, Car car, Date dateFrom, Date dateTo,
			String attachment, Date dateregistered, Boolean confirmed) {
		this.bindrole = bindrole;
		this.car = car;
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
		this.attachment = attachment;
		this.dateregistered = dateregistered;
		this.confirmed = confirmed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idrent", unique = true, nullable = false)
	public Integer getIdrent() {
		return this.idrent;
	}

	public void setIdrent(Integer idrent) {
		this.idrent = idrent;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "bindrole_idbindrole", nullable = false)
	public Bindrole getBindrole() {
		return this.bindrole;
	}

	public void setBindrole(Bindrole bindrole) {
		this.bindrole = bindrole;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "car", nullable = false)
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_from", length = 10)
	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_to", length = 10)
	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	@Column(name = "attachment", length = 300)
	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateregistered", length = 10)
	public Date getDateregistered() {
		return this.dateregistered;
	}

	public void setDateregistered(Date dateregistered) {
		this.dateregistered = dateregistered;
	}

	@Column(name = "confirmed")
	public Boolean getConfirmed() {
		return this.confirmed;
	}

	public void setConfirmed(Boolean confirmed) {
		this.confirmed = confirmed;
	}

}
