package pl.com.mnemonic.entities;
// default package
// Generated 2015-04-12 11:10:53 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "renting", uniqueConstraints = @UniqueConstraint(columnNames = "role_code"))
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idrole;
	private String roleCode;
	private String roleName;
	private String roleDescription;
	private Set<Bindpage> bindpages = new HashSet<Bindpage>(0);
	private Set<Bindrole> bindroles = new HashSet<Bindrole>(0);

	public Role() {
	}

	public Role(String roleCode, String roleName) {
		this.roleCode = roleCode;
		this.roleName = roleName;
	}

	public Role(String roleCode, String roleName, String roleDescription,
			Set<Bindpage> bindpages, Set<Bindrole> bindroles) {
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.roleDescription = roleDescription;
		this.bindpages = bindpages;
		this.bindroles = bindroles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idrole", unique = true, nullable = false)
	public Integer getIdrole() {
		return this.idrole;
	}

	public void setIdrole(Integer idrole) {
		this.idrole = idrole;
	}

	@Column(name = "role_code", unique = true, nullable = false, length = 45)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "role_name", nullable = false, length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_description", length = 45)
	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Bindpage> getBindpages() {
		return this.bindpages;
	}

	public void setBindpages(Set<Bindpage> bindpages) {
		this.bindpages = bindpages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Bindrole> getBindroles() {
		return this.bindroles;
	}

	public void setBindroles(Set<Bindrole> bindroles) {
		this.bindroles = bindroles;
	}

}
